# Generated by Django 3.2.4 on 2021-06-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('current_price', models.FloatField(blank=True)),
                ('old_price', models.FloatField(blank=True, default=0)),
                ('target_price', models.FloatField(default=100000)),
                ('receiver_email', models.EmailField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
