# Generated by Django 3.2.4 on 2021-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target_price',
            field=models.FloatField(default=100000),
        ),
    ]
